extends:
  - htmlacademy/vanilla
  - plugin:astro/recommended

parserOptions:
  ecmaVersion: 2022
  sourceType: module

env:
  browser: true
  es2022: true

overrides:
  - files:
      - "*.astro"
    parser: astro-eslint-parser
    parserOptions:
      parser: "@typescript-eslint/parser"
    globals:
      ImageMetadata: readonly
      Astro: readonly
    rules:
      no-unused-vars: warn
