extends:
  - htmlacademy/vanilla
  - plugin:astro/recommended

parserOptions:
  ecmaVersion: 2022
  sourceType: module

env:
  browser: true
  es2022: true

overrides:
  - files:
      - "*.astro"
    parser: astro-eslint-parser
    rules:
      no-unused-vars: warn
